export type Field = { key: string; label: string; type?: 'text' | 'textarea' | 'date' | 'time' | 'number' | 'select'; options?: string[]; required?: boolean; min?: number; max?: number };
export type Section = { title: string; fields: Field[] };
export type Template = { id: string; title: string; code?: string; description: string; kind: 'ficha' | 'planilla'; period: 'date' | 'month' | 'year'; sections: Section[]; columns?: Field[]; signatures?: string[]; note?: string };
const f = (key: string, label: string, type: Field['type'] = 'text', required = false): Field => ({ key, label, type, required });
const choice = (key: string, label: string, options: string[]): Field => ({ key, label, type: 'select', options });
const yes = (key: string, label: string) => choice(key, label, ['Sí', 'No']);
const area = (key: string, label: string) => f(key, label, 'textarea');
const vital = [f('bloodPressure', 'Presión arterial (mmHg)'), f('heartRate', 'Frecuencia cardiaca (lpm)', 'number'), f('respiratoryRate', 'Frecuencia respiratoria (rpm)', 'number'), f('temperature', 'Temperatura (°C)', 'number')];
const names = [f('paternal', 'Apellido paterno'), f('maternal', 'Apellido materno'), f('names', 'Nombres')];
const sexAge = [choice('sex', 'Sexo', ['F', 'M']), f('age', 'Edad', 'number')];
const identity = [...names, f('date', 'Fecha', 'date', true), f('time', 'Hora', 'time'), f('birthDate', 'Fecha de nacimiento', 'date'), f('age', 'Edad', 'number'), f('civilStatus', 'Estado civil'), f('department', 'Gerencia'), f('occupation', 'Profesión - ocupación'), f('company', 'Empresa'), f('address', 'Domicilio'), f('phone', 'Teléfono - celular')];
const risks = ['Físicos', 'Químicos', 'Biológicos', 'Psicosociales', 'Ergonómicos'];
const aptitude = () => choice('aptitude', 'Aptitud laboral', ['APTO', 'APTO CON RESTRICCIONES', 'NO APTO']);
export const months = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
export const templates: Template[] = [
  { id: 'historia', title: 'Historia clínica', description: 'Atención individual con los nueve apartados del formato original.', kind: 'ficha', period: 'date', sections: [
    { title: '1. Datos de identificación', fields: identity },
    { title: '2. Antecedentes personales (hábitos y costumbres)', fields: [area('personalHistory', 'Antecedentes personales')] },
    { title: '3. Antecedentes ocupacionales', fields: [area('occupationalHistory', 'Antecedentes ocupacionales')] },
    { title: '4. Antecedentes familiares', fields: [area('familyHistory', 'Antecedentes familiares')] },
    { title: '5. Motivo de consulta', fields: [{ ...area('reason', 'Motivo de consulta'), required: true }] },
    { title: '6. Enfermedad actual', fields: [area('illness', 'Enfermedad actual')] },
    { title: '7. Examen físico', fields: [...vital, area('examination', 'Examen físico')] },
    { title: '8. Diagnóstico', fields: [{ ...area('diagnosis', 'Diagnóstico'), required: true }] },
    { title: '9. Conducta', fields: [area('conduct', 'Conducta'), f('doctor', 'Médico tratante', 'text', true)] },
    { title: 'Datos para el registro de consultas', fields: [choice('kind', 'Tipo de atención', ['Consulta','Reconsulta']), f('workSchedule', 'Horario de trabajo'), choice('sex', 'Sexo', ['F','M']), area('treatment', 'Tratamiento'), area('referral', 'Interconsulta'), area('recommendations', 'Observaciones o recomendaciones')] },
  ], signatures: ['Firma del médico', 'Sello del médico'] },
  { id: 'consultas', title: 'Registro de consultas médicas', description: 'Planilla diaria o mensual, con atenciones incorporadas desde Historia clínica.', kind: 'planilla', period: 'month', sections: [], columns: [f('date','Fecha','date',true),f('time','Hora','time'),f('workSchedule','Horario de trabajo'),...names,...sexAge,area('diagnosis','Diagnóstico'),choice('kind','Consulta / Reconsulta',['Consulta','Reconsulta']),area('treatment','Tratamiento'),f('doctorSignature','Firma médico'),f('patientSignature','Firma paciente'),area('referral','Interconsulta'),area('recommendations','Observaciones o recomendaciones')] },
  { id: 'ocupacional', title: 'Ficha de salud ocupacional', code: 'RG-143-B PG-1-DGSMS-70', description: 'Evaluación de ingreso, periódica y postocupacional del trabajador.', kind: 'ficha', period: 'date', sections: [
    { title: '1. Información general', fields: [f('place','Lugar'),f('entryDate','Fecha ingreso','date'),f('registration','Matrícula'),f('fullName','Nombre y apellido','text',true),f('ci','CI'),f('birthDate','Fecha de nacimiento','date'),f('phone','Teléfono'),f('bloodGroup','Grupo sanguíneo y Rh'),f('address','Dirección'),f('age','Edad','number'),f('contact','Contacto'),f('contactPhone','Teléfono de contacto')] },
    { title: '2. Riesgos ocupacionales', fields: risks.map((r,i)=>area('risk'+i,r)) },
    { title: '3. Antecedentes personales', fields: ['Patológicos','Quirúrgicos','Traumáticos','Tóxicos','Alérgicos','Comentarios'].map((r,i)=>area('antecedent'+i,r)) },
    { title: '4. Examen médico preocupacional', fields: [f('preDate','Fecha','date'),area('diagnosis','Diagnóstico'),aptitude(),area('recommendations','Recomendación')] },
    { title: '5. Examen médico periódico', fields: [f('periodicDate','Fecha','date'),area('periodicChanges','Cambios significativos del EMP'),area('periodicConduct','Observaciones y conducta del EMP')] },
    { title: '6. Examen médico postocupacional', fields: [f('postDate','Fecha','date'),area('postChanges','Cambios significativos'),area('postConduct','Observaciones y conducta')] },
  ] },
  { id: 'periodica', title: 'Historia clínica periódica ocupacional', description: 'Evaluación ocupacional completa, conservando cada revisión anterior.', kind: 'ficha', period: 'date', sections: [
    { title: '1. Datos de identificación general', fields: [f('fullName','Apellidos y nombres','text',true),f('ci','CI'),f('birthDate','Fecha de nacimiento','date'),...sexAge,f('civilStatus','Estado civil'),f('education','Grado de instrucción'),f('address','Domicilio actual'),f('company','Razón social / empresa'),f('nit','NIT'),f('occupation','Puesto de trabajo actual'),f('department','Área / centro'),f('date','Fecha de evaluación','date',true),f('previousDate','Fecha examen anterior','date')] },
    { title: '2. Anamnesis y evolución de síntomas', fields: [f('timeInPosition','Tiempo en el puesto actual'),yes('changedDuties','Cambios en funciones'),area('tasks','Descripción resumida de tareas actuales'),yes('newSymptoms','Síntoma, molestia o signo nuevo desde la última evaluación'),area('symptoms','Especifique'),choice('improvesOutside','Los síntomas mejoran fuera de la jornada laboral',['Sí','No','No aplica']),area('symptomNotes','Observaciones')] },
    { title: '3. Verificación de exposición a factores de riesgo ocupacional', fields: [risks[0],risks[1],risks[2],risks[4],risks[3]].flatMap((r,i)=>[yes('exposed'+i,'Exposición: '+r),area('exposure'+i,'Detalle / fuente: '+r)]).concat([choice('ppeUse','Uso correcto y periódico de EPP',['Siempre','A veces','Nunca','No requiere'])]) },
    { title: '4. Antecedentes de salud recientes (desde el último examen)', fields: [area('recentHistory','Nuevas enfermedades diagnosticadas, cirugías, accidentes o internaciones'),yes('tobacco','Tabaco'),f('tobaccoFrequency','Frecuencia de tabaco'),yes('alcohol','Alcohol'),f('alcoholFrequency','Frecuencia de alcohol')] },
    { title: '5. Examen físico y signos vitales', fields: [...vital,f('weight','Peso (kg)','number'),f('height','Talla (m)','number'),f('bmi','IMC','number'),f('nutrition','Estado nutricional'),...['Piel y faneras','Agudeza visual / ojos','Otoscopia / audición','Sistema respiratorio','Sistema cardiovascular','Sistema osteomuscular'].flatMap((r,i)=>[choice('system'+i,r,['Normal','Hallazgo']),area('finding'+i,'Descripción del hallazgo: '+r)])] },
    { title: '6. Resultados de pruebas complementarias y laboratorio', fields: ['Hemograma / glicemia','Audiometría tonal','Espirometría','Otros (Rayos X, Tox.)'].flatMap((r,i)=>[choice('test'+i,r,['Normal','Alterado']),area('testDetail'+i,'Detalle: '+r)]) },
    { title: '7. Diagnósticos definitivos / sospechas', fields: [{...area('diagnosis','Diagnóstico 1'),required:true},area('diagnosis2','Diagnóstico 2')] },
    { title: '8. Calificación de aptitud médica ocupacional', fields: [aptitude(),area('recommendations','Recomendaciones médicas y restricciones laborales'),f('doctor','Médico evaluador','text',true),f('license','Registro / colegiatura médica')] },
  ], signatures: ['Firma y sello del médico evaluador', 'Firma y huella del trabajador · Notificación y conformidad'] },
  { id: 'alcotest', title: 'Control alcotest', description: 'Pruebas pasivas y directas con examinador y observaciones.', kind: 'planilla', period: 'month', sections: [], columns: [f('date','Fecha','date',true),f('time','Hora','time'),f('names','Nombre'),f('paternal','Apellido paterno'),f('maternal','Apellido materno'),...sexAge,f('occupation','Puesto de trabajo'),f('passive','Prueba pasiva'),f('direct','Prueba directa'),f('examiner','Examinador'),area('sampleHistory','Antecedente de toma de muestra'),area('currentMedication','Medicación actual'),area('observations','Observaciones')], note: 'Se realizarán pruebas pasivas; en caso de dar positivo se confirmará con la prueba directa (utilización de boquilla desechable), determinando el valor de alcotest. La política de ingesta de alcohol en ENDE DE ORURO es “0”.' },
  { id: 'bajas', title: 'Informe bajas médicas', description: 'Registro de bajas por unidad y año, con inicio, alta, días y horas.', kind: 'planilla', period: 'year', sections: [{title:'Encabezado',fields:[f('unit','Unidad')]}], columns: [f('date','Fecha','date',true),f('code','Código'),area('diagnosis','Diagnóstico'),yes('scheduled','Programada'),yes('emergency','Emergencia'),f('startDate','Fecha de inicio','date'),f('endDate','Fecha de alta','date'),f('days','Días de baja','number'),f('hours','Horas de baja','number'),area('pathology','Enfermedad y/o patología'),area('treatment','Tratamiento clínico o quirúrgico'),area('recommendations','Observaciones y/o recomendación')] },
  { id: 'cronicos', title: 'Control de enfermedades crónicas', code:'RG-62-A PG-1-DGSMS-70', description: 'Seguimiento anual, con una columna por cada mes.', kind:'planilla',period:'year',sections:[],columns:[f('fullName','Apellidos y nombres','text',true),yes('dmt','DMT'),yes('hta','HTA'),f('other','Otra patología'),f('currentValue','Valor actual'),area('treatment','Tratamiento'),...months.map((m,i)=>f('month'+(i+1),m)),area('observations','Observaciones'),f('signature','Firma')] },
  { id:'critico',title:'Control médico trabajos críticos',description:'Mediciones sucesivas por trabajador y tipo de trabajo.',kind:'planilla',period:'month',sections:[],columns:[f('date','Fecha','date',true),f('time','Hora','time'),f('fullName','Apellidos y nombres','text',true),f('company','Empresa'),f('department','Área'),f('workType','Tipo de trabajo'),...Array.from({length:5},(_,i)=>[f('controlDate'+i,'Fecha control '+(i+1),'date'),f('pa'+i,'PA '+(i+1)),f('pulse'+i,'Pulso '+(i+1),'number'),f('sat'+i,'Sat. O₂ '+(i+1)+' (%)','number')]).flat(),area('observations','Observaciones')] },
  { id:'farmacia',title:'Control medicamentos en farmacia · Unidad de salud',code:'RG-65-A PG-1-DGSMS-70',description:'Ingresos y consumos diarios de farmacia, saldo y vencimiento.',kind:'planilla',period:'month',sections:[{title:'Observaciones',fields:[area('observations','Observaciones')]}],columns:[f('medication','Nombre del medicamento','text',true),f('presentation','Presentación'),f('opening','Saldo inicial','number'),f('incoming','Ingreso de medicamentos','number'),...Array.from({length:31},(_,i)=>f('day'+(i+1),String(i+1),'number')),f('used','Total usados','number'),f('balance','Saldo a fin de mes','number'),f('expiry','Fecha de vencimiento','date')],note:'Saldo inicial + ingresos − total usado = saldo final. Los consumos de esta planilla no generan otra salida del almacén; las entregas del almacén se registran en Actas.' },
];

export type FormDataValues = { fields: Record<string,string>; rows: Record<string,string>[] };
export type MedicalDocument = { id:string; template_id:string; worker_id:string|null; worker_snapshot:Record<string,string>; period:string; status:'draft'|'final'; revision:number; data:FormDataValues; author_name:string; created_at:string; updated_at:string; finalized_at:string|null; correction_of:string|null; correction_reason:string; source_document_id:string|null; source_managed?:boolean; superseded?:boolean };
export type DocumentFilter = { template?:string; worker?:string; from?:string; to?:string; status?:string; offset?:number };
export const getTemplate = (id:string) => templates.find(t=>t.id===id);
export const today = () => new Intl.DateTimeFormat('sv-SE',{timeZone:'America/La_Paz'}).format(new Date());
export function periodDate(value:string) { return value.length===4?value+'-01-01':value.length===7?value+'-01':value; }
export function daysInMonth(period:string) { const [y,m]=period.split('-').map(Number); return new Date(Date.UTC(y,m,0)).getUTCDate(); }
export function pharmacyRow(row:Record<string,string>, period:string):Record<string,string> {
  const used=Array.from({length:daysInMonth(period)},(_,i)=>Number(row['day'+(i+1)]||0)).reduce((a,b)=>a+b,0);
  const balance=Number(row.opening||0)+Number(row.incoming||0)-used;
  return {...row,used:String(Number(used.toFixed(4))),balance:String(Number(balance.toFixed(4)))};
}
export function documentLabel(doc:MedicalDocument) { return doc.worker_snapshot.full_name || doc.data.fields.fullName || (doc.data.rows.length+' registros'); }
